const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../index.js'),'utf8');
const functions=['roundCapacity','roundBlockReason','collect'].map(name=>source.split('\n').find(s=>s.startsWith('function '+name+'(')||s.startsWith('async function '+name+'('))).join('\n');
const ctx={};vm.createContext(ctx);vm.runInContext(functions+'\nglobalThis.api={roundCapacity,roundBlockReason,collect};',ctx);const a=ctx.api;
const state=(stage,san=90,rage=false)=>({沈挽昼:{核心状态:{异化阶段:stage,理智值:san,侵蚀度:85,躁变值:10,是否狂暴:rage,抑制剩余分钟:120}}});
assert.equal(a.roundCapacity(state('深度异化')),1);const stale=state('稳定');stale.沈挽昼.核心状态.躁变值=60;assert.equal(a.roundCapacity(stale),0);assert.match(a.roundBlockReason(stale),/半狂暴/);stale.沈挽昼.核心状态.躁变值=80;assert.match(a.roundBlockReason(stale),/失去稳定行动/);assert.equal(a.roundBlockReason(state('深度异化')),'');assert.equal(a.roundCapacity(state('深度异化',90,true)),0);assert.ok(a.roundBlockReason(state('深度异化',90,true)));assert.ok(a.roundBlockReason(state('稳定',30)));assert.equal(a.roundBlockReason(state('稳定',31)),'');
(async()=>{await assert.rejects(a.collect('cache','安全屋储备'),/当前携带库存/);await assert.rejects(a.collect('cache','任意键'),/当前携带库存/);console.log('PASS explore: conscious deep infection, active rage, sanity boundary, destination validation')})().catch(e=>{console.error(e);process.exitCode=1});
const receiptFn=source.slice(source.indexOf('function roundReceiptAcknowledged('),source.indexOf('function availableResource('));
const resourceFn=source.slice(source.indexOf('function availableResource('),source.indexOf('function roundRemaining('));
let chat=[{is_user:false,mes:'开场'}];
const isolated={SillyTavern:{get chat(){return chat}},ensureExplore:s=>s.地图.探索系统,resourceCost:(_loc,items)=>items.reduce((n,item)=>n+item.cost,0),dynamic:s=>s.地图.地点动态[Object.keys(s.地图.地点动态)[0]],clamp:(n,min,max)=>Math.min(max,Math.max(min,n)),Number,String,Array,Math};vm.createContext(isolated);vm.runInContext(receiptFn+resourceFn+'\nglobalThis.check={roundReceiptAcknowledged,availableResource};',isolated);
const round={轮次ID:'R-123',起始楼层:0,解锁楼层:2};chat.push({is_user:true,mes:'别的对话'},{is_user:false,mes:'又一层'});assert.equal(isolated.check.roundReceiptAcknowledged(round),false);
chat.push({is_user:true,mes:'[探索行动轮已结算]\n轮次ID：R-other'},{is_user:false,mes:'继续'});assert.equal(isolated.check.roundReceiptAcknowledged(round),false);
chat.push({is_user:true,mes:'[探索行动轮已结算]\n轮次ID：R-123'});assert.equal(isolated.check.roundReceiptAcknowledged(round),false);
chat.push({is_user:false,mes:'正文承接搜索'});assert.equal(isolated.check.roundReceiptAcknowledged(round),true);
const reservationState={地图:{地点动态:{测试地点:{资源指数:90}},探索系统:{待收取:[{地点:'测试地点',物品:[{cost:10}]},{地点:'别处',物品:[{cost:30}]},{地点:'测试地点',物品:[{cost:7}]}]}}};assert.equal(isolated.check.availableResource(reservationState,'测试地点'),73);
console.log('PASS explore: receipt must precede assistant response; pending batches reserve resource');

const parentSource=source.split('\n').find(line=>line.startsWith('function parentHiddenEvent('));
const parentCtx={ensureParentShadow:sd=>sd.暗线.父母};vm.createContext(parentCtx);vm.runInContext(parentSource+'\nglobalThis.parentHiddenEvent=parentHiddenEvent;',parentCtx);
const parentState={世界:{灾变日:9},暗线:{父母:{状态:'未寻获',改道已确认:false}}};
assert.equal(parentCtx.parentHiddenEvent(parentState,'河西社区医院','A08',2,0).type,'death');
parentState.暗线.父母.改道已确认=true;assert.equal(parentCtx.parentHiddenEvent(parentState,'河西社区医院','A08',2,0),null);
parentState.世界.灾变日=5;assert.equal(parentCtx.parentHiddenEvent(parentState,'槐安公寓','A01',1,0),null);
parentState.世界.灾变日=7;assert.equal(parentCtx.parentHiddenEvent(parentState,'河西旧街','A05',3,0),null);
console.log('PASS parent: confirmed reroute prevents default day-nine death; unchanged history retains it');

const advanceSource=source.split('\n').find(line=>line.startsWith('function advanceTime('));
const cureCtx={parseUtc:Date.parse,fmtUtc:n=>new Date(n).toISOString(),period:()=> '夜间',START:'2024-10-27T19:42:00Z',CURE:'2026-04-27T19:42:00Z'};
vm.createContext(cureCtx);vm.runInContext(advanceSource+'\nglobalThis.advanceTime=advanceTime;',cureCtx);
const cureState={世界:{当前时间:'2026-04-28T12:00:00Z',解药:{研发完成时间:'2026-04-27T19:42:00Z',状态:'已稳定',终局阶段:'已稳定'}},沈挽昼:{核心状态:{抑制剩余分钟:0}}};
cureCtx.advanceTime(cureState,15);assert.equal(cureState.世界.解药.状态,'已稳定');assert.equal(cureState.世界.解药.终局阶段,'已稳定');
const waiting={世界:{当前时间:'2026-04-27T19:41:00Z',解药:{研发完成时间:'2026-04-27T19:42:00Z',状态:'研发中',终局阶段:'等待研发'}},沈挽昼:{核心状态:{抑制剩余分钟:0}}};
cureCtx.advanceTime(waiting,2);assert.equal(waiting.世界.解药.状态,'研发完成');assert.equal(waiting.世界.解药.终局阶段,'寻找发放点');
console.log('PASS cure: exploration clock advances research but preserves completed treatment');
